project:
  type: website
  output-dir: docs
website:
  title: "Brandon Pizer"
  favicon: img/icon_image.jpg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: docs/Brandon Pizer Resume 2025.pdf
        text: Resume
      - href: https://github.com/brandonpizer
        icon: github
  page-footer: 
    background: light
    left: Copyright 2025, Brandon Pizer
    right: Built with RStudio, Quarto, Git

format:
  html:
    theme: superhero
    toc: true

editor: visual

